version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3000:3000"
      - "50051:50051"
    volumes:
      - profile-data:/usr/local/bin/data
    networks:
      - profiling-network
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  daemon:
    build:
      context: .
      dockerfile: Dockerfile.daemon
    ports:
      - "3001:3001"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - profiling-network
    environment:
      - RUST_LOG=info
      - SERVER_URL=http://server:3000
      - GRPC_URL=http://server:50051

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - profiling-network
    environment:
      - VITE_API_URL=http://localhost:3000
      - NODE_ENV=production

networks:
  profiling-network:
    driver: bridge

volumes:
  profile-data:
    driver: local 