FROM rust:1.75 as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --bin server --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl-dev ca-certificates curl && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/target/release/server /usr/local/bin/server
VOLUME ["/usr/local/bin/data"]

HEALTHCHECK --interval=30s --timeout=3s \
  CMD curl -f http://localhost:3000/health || exit 1

EXPOSE 3000 50051
CMD ["server"] 