FROM rust:1.75 as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --bin daemon --release

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl-dev ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/src/app/target/release/daemon /usr/local/bin/daemon
EXPOSE 3001
CMD ["daemon"] 